### ISSUE TITLE
Saving Circles Spec

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/saving-circles#1]
## Introduction
Savings Circles,  also known by many other names in various cultures,  allows groups of people to collectively save and distribute funds in a predetermined order. Each member is eligible for receiving the pool of deposits when their turn arrives.

Implementing a saving circle using blockchain technology allows for improvements in trust & transparency, automated execution and increased accessibility.

--- 
## Technical Implementation

```mermaid 
classDiagram

    class CircleManager {

        +Circle[] circles
        +IERC20[] whitelistedTokens

        +mapping circleMemberships

        +initialize()

        +addCircle()

        +deposite()

        +withdraw()

        +withdrawable()

        +circleInfo()

        +balancesForCircle()

		+decomissionCircle()
		
		+depositFor()

    }

    class Circle {

        +address owner

        +string name

        +address[] members

        +uint256 currentIndex

        +uint256 depositAmount

        +IERC20 tokenAddress

        +uint256 depositInterval

        +mapping balances
        +uint256 circleStart 
        +uint256 numWithdrawals

    }

    class OwnableUpgradeable {

        +address owner

        +transferOwnership()

    }

    class IERC20 {

        +transfer()

        +transferFrom()

        +approve()

    }



    CircleManager --|> OwnableUpgradeable

    CircleManager --* Circle

    Circle ..> IERC20

```

### Circle Manager
The CircleManager contract is responsible for allowing users to create, join and interact with a saving circle. The Circle manager can whitelist ERC20 tokens to integrate.  The Circle Manager can also decomission a circle, which returns all deposited funds to members. The Circle Manager also allows to deposit for a circle member, to account for mistakes and unforeseen circumstances. 

### Circle Struct
The Circle struct is designed with a fixed membership with predefined contribution amounts. It keeps track of the current claimer, and deposit balances for each member. 

--- 
#### Circle Creation 
A user can permissionlessly create a circle by specifying all associated circle parameters. 

```mermaid 
sequenceDiagram
autonumber

actor CircleOwner


participant UI

participant SavingsCircle


  

CircleOwner->>UI: Initiates circle creation

CircleOwner->>UI: Inputs circle details<br/>(name, members, token, amount,contributionInterval)

UI->>SavingsCircle: addCircle()

Note right of SavingsCircle: Circle is created<br/>Members are registered
```

### Depositing to a circle
Depositing is performed using an approval mechanism, as this assures the user explicitly understands and agrees to participating in the circle. 

```mermaid 
sequenceDiagram
autonumber

actor Member

participant UI

participant SavingsCircle

participant ERC20Token

  

Member->>UI: Initiates contribution
note over ERC20Token : This is only required once
UI->>ERC20Token: Requests token approval

Member->>ERC20Token: Approves tokens

UI->>SavingsCircle: deposit()

SavingsCircle->>ERC20Token: transferFrom()

ERC20Token-->>SavingsCircle: Confirms transfer

SavingsCircle-->>UI: Updates balance

UI-->>Member: Confirms deposit
```

### Withdrawal flow 
By viewing the smart contract state we can reflect to the circle member whether they can withdraw. If the user has an eligible withdrawal balance, then a transaction to claim the balance can be executed.
```mermaid 
sequenceDiagram
autonumber

actor Member

participant UI

participant SavingsCircle

participant ERC20Token

Member->>UI: Checks withdrawal eligibility

UI->>SavingsCircle: withdrawable()

SavingsCircle-->>UI: Returns eligibility

  

alt Can Withdraw

Member->>UI: Initiates withdrawal

UI->>SavingsCircle: withdraw()

SavingsCircle->>ERC20Token: transfer()

ERC20Token-->>Member: Sends tokens

SavingsCircle-->>UI: Updates circle state

UI-->>Member: Confirms withdrawal

else Cannot Withdraw

UI-->>Member: Shows error message

end
```
### Necessary Frontend Components  

- Circle Creation 
	- Define deposit 
	- Define name
	- Define members
	- Define deposit amount
	- Define token 
	- Define deposit interval 
Reference: 
![Image](https://github.com/user-attachments/assets/b1544ab5-b405-4aaf-86f4-caf8c63621c2)

- Circles Overview
	- Shows circles which the member belongs to
	- On clicking leads a project, leads to the circle interaction page 
- Circle Interaction 
	- Show eligible balance
	- Allow to withdraw if eligible 
	- Show whether interval deposit has been made or not 
	- Allow to deposit interval amount. 
## Concessions of the Implementation

- No mechanism to handle member defaults or leaving the circle
- Fixed deposit amounts throughout the circle's lifetime
- No interest or reward mechanisms
- No partial withdrawals or emergency withdrawals
- No mechanism to update or remove members

**Comment by RonTuretzky** [comment]
Relevant for v2 https://en.wikipedia.org/wiki/Chama_(investment)

**Comment by diterra-code** [comment]
Dropping some inspo for V2:

Collected from wiki:



**Risks**
- Merry Go Round Chamas are subject to collapsing if one or more members collect early in the rotation, but drop out before the end of the rotation.

Solution:
- This is how they solve the risk issue associated with early members rugging the older members: ROSCA chamas minimize this risk by giving the most trusted members the early rotations and the least trusted members the latter rotations

**Incentive**

Group organizer fee: The one that starts the group and does reminders gets a small fee.

**Reputation system:**

Get points if you return. Gives you a saving cricle trust score and allows you to get chance to get earlier in line at every rotation.

**Little return on first pay:**

"The fund starts at an announced date and continues for the number of months equal to the number of subscribers. Each month, the subscribers put in their monthly installments into the pot. Then, an open auction is conducted to determine the lowest sum a subscriber is willing to take that month. For example, if the monthly installment is ₹1000 and there are 50 members, the pot in the first month will contain ₹50,000. If the auction determines a winner who is willing to accept ₹45,000 for that month, the surplus ₹5,000 is distributed to the other 49 members, after subtracting fees paid to the organizer. The subscriber who won the auction was able to access ₹45,000 in the first month and the others benefited in their share of the ₹5,000 surplus. The process repeats, distributing the auction amount to one member each month. All of the other subscribers, including the ones who took their share in a previous month, continue paying the monthly installments."

**Comment by RonTuretzky** [comment]
https://en.wikipedia.org/wiki/Chit_fund
